import { ArrowRight, CheckCircle2, Clock3, LogIn, MapPinned, Medal, Recycle } from 'lucide-react'
import { Link } from 'react-router-dom'

export default function Home() {
  const links = [
    { to: '/mapa', label: 'Encontrar ponto de coleta', icon: MapPinned },
    { to: '/historico', label: 'Consultar histórico', icon: Clock3 },
    { to: '/login', label: 'Acessar o login', icon: LogIn },
  ]

  return <div className="page home-page"><div className="home-grid"><section className="welcome-panel surface"><span className="hero-badge"><Recycle size={15} /> EletroRecicla</span><p className="eyebrow text-white-50">Descarte responsável</p><h1>Seu eletrônico ainda pode ter um bom destino.</h1><p>Localize pontos de coleta aprovados, escolha o melhor local e acompanhe cada descarte em um só lugar.</p><div className="welcome-actions"><Link className="btn-eco text-decoration-none" to="/mapa"><MapPinned size={19} />Encontrar ponto próximo</Link><Link className="hero-secondary" to="/historico">Ver meu histórico <ArrowRight size={17} /></Link></div></section><aside className="quick-panel surface"><span className="panel-number">01</span><h2>Acesso rápido</h2><p className="panel-copy">Tudo o que você precisa para começar seu descarte.</p><div className="quick-list">{links.map(({to,label,icon:Icon}) => <Link className="quick-link" to={to} key={to}><Icon size={20} />{label}<ArrowRight size={17} /></Link>)}</div></aside></div><section className="process-section"><div className="section-heading"><div><p className="eyebrow">Como funciona</p><h2>Do eletrônico parado ao descarte correto</h2></div><CheckCircle2 size={30} /></div><div className="info-strip surface"><div className="info-item"><span className="step-number">01</span><span className="info-icon"><MapPinned /></span><h3>Localize</h3><p>Visualize pontos de coleta no mapa e selecione o mais adequado.</p></div><div className="info-item"><span className="step-number">02</span><span className="info-icon"><Recycle /></span><h3>Descarte</h3><p>Leve seu resíduo eletrônico até uma empresa parceira aprovada.</p></div><div className="info-item"><span className="step-number">03</span><span className="info-icon"><Medal /></span><h3>Acompanhe</h3><p>Consulte os registros e pontos gerados por seus descartes.</p></div></div></section><section className="home-cta"><div><p className="eyebrow">Comece agora</p><h2>Encontre o ponto de coleta mais adequado.</h2></div><Link className="btn-eco text-decoration-none" to="/mapa">Explorar mapa <ArrowRight size={18} /></Link></section></div>
}
